
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: "{{ data.version }}"

source:
  path: ..

  #{% set git_rev = "v" + data.version %}
  #git_rev: {{ git_rev }}
  #git_url: https://github.com/fastai/ipyexperiments

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

# nvidia-ml-py3 is in the fastai channel only
requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - ipython
    - nvidia-ml-py3
    - psutil

test:
  imports:
    - ipyexperiments

about:
  home: {{ data.get('url') }}
  license: {{ data['license'] }}
  license_family: APACHE
  license_file: LICENSE.txt
  summary: {{ data['description'] }}
  description: {{ data['description'] }}
  doc_url: {{ data.get('url') }}
  dev_url: {{ data.get('url') }}

extra:
  recipe-maintainers: ''
